// Code Generated by Sidekick is for learning and experimentation purposes only.
import { useState } from "react";
import { ALL_QUESTIONS } from "./questions";

const PASSWORD = "cisvr2025"; // 🔑 Change this to your preferred password
const MODES = { HOME: "home", EXAM: "exam" };

function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

// ---- PASSWORD GATE ----
function PasswordGate({ children }) {
  const [input, setInput] = useState("");
  const [granted, setGranted] = useState(false);
  const [error, setError] = useState(false);

  function handleSubmit(e) {
    e.preventDefault();
    if (input === PASSWORD) {
      setGranted(true);
    } else {
      setError(true);
      setInput("");
    }
  }

  if (granted) return children;

  return (
    <div style={{ display: "flex", flexDirection: "column", alignItems: "center", marginTop: 100 }}>
      <h2>🔒 CIS-VR Practice</h2>
      <p>Enter the password to access the practice exam:</p>
      <form onSubmit={handleSubmit} style={{ display: "flex", gap: 8 }}>
        <input
          type="password"
          value={input}
          onChange={(e) => { setInput(e.target.value); setError(false); }}
          placeholder="Enter password"
          style={{ padding: "8px 12px", fontSize: 16 }}
          autoFocus
        />
        <button type="submit" style={{ padding: "8px 16px" }}>Enter</button>
      </form>
      {error && <p style={{ color: "red", marginTop: 8 }}>❌ Incorrect password. Try again.</p>}
    </div>
  );
}

// ---- QUESTION CARD ----
function QuestionCard({ q, sel, isSubmitted, correct, onToggle, onSubmit }) {
  const S = {
    card: { border: "1px solid #ccc", padding: 16, marginBottom: 16 },
    qBadge: { fontWeight: "bold", color: "blue" },
    qNum: { fontWeight: "bold" },
    qText: { fontSize: 18, margin: "8px 0" },
    opts: { display: "flex", flexDirection: "column", gap: 8 },
    opt: { padding: 8, textAlign: "left", border: "1px solid #ddd", cursor: "pointer" },
    optSel: { backgroundColor: "#def" },
    optOk: { backgroundColor: "#afa" },
    optBad: { backgroundColor: "#faa" },
    optDim: { color: "#999" },
    optLbl: { marginRight: 8, fontWeight: "bold" },
    tick: { marginLeft: 8, color: "green" },
    cross: { marginLeft: 8, color: "red" },
    submitBtn: { marginTop: 12, padding: "8px 16px", cursor: "pointer" },
    submitBtnOff: { marginTop: 12, padding: "8px 16px", color: "#999", cursor: "not-allowed" },
    fbOk: { marginTop: 12, color: "green", fontWeight: "bold" },
    fbBad: { marginTop: 12, color: "red", fontWeight: "bold" }
  };

  return (
    <div style={S.card}>
      <div style={S.qBadge}>{q.type === "multi" ? "Multiple Select" : "Single Select"}</div>
      <div style={S.qNum}>Question {q.id}</div>
      <div style={S.qText}>{q.q}</div>
      <div style={S.opts}>
        {q.opts.map((opt, i) => {
          const isSel = sel.includes(opt);
          const isAns = q.ans.includes(opt);
          let st = S.opt;
          if (isSubmitted) {
            if (isAns) st = { ...S.opt, ...S.optOk };
            else if (isSel) st = { ...S.opt, ...S.optBad };
            else st = { ...S.opt, ...S.optDim };
          } else if (isSel) {
            st = { ...S.opt, ...S.optSel };
          }
          return (
            <button key={i} style={st} onClick={() => onToggle(q.id, opt)} disabled={isSubmitted}>
              <span style={S.optLbl}>{String.fromCharCode(65 + i)}</span>
              <span>{opt}</span>
              {isSubmitted && isAns && <span style={S.tick}>✓</span>}
              {isSubmitted && isSel && !isAns && <span style={S.cross}>✗</span>}
            </button>
          );
        })}
      </div>
      {!isSubmitted && (
        <button
          style={sel.length > 0 ? S.submitBtn : S.submitBtnOff}
          onClick={() => onSubmit(q.id)}
          disabled={sel.length === 0}
        >
          Submit Answer
        </button>
      )}
      {isSubmitted && (
        <div style={correct ? S.fbOk : S.fbBad}>
          {correct ? "✓ Correct!" : `✗ Incorrect. Correct: ${q.ans.join(", ")}`}
        </div>
      )}
    </div>
  );
}

// ---- MAIN APP ----
function App() {
  const [mode, setMode] = useState(MODES.HOME);
  const [examConfig, setExamConfig] = useState({ count: 20, randomize: true });
  const [questions, setQuestions] = useState([]);
  const [answers, setAnswers] = useState({});
  const [submitted, setSubmitted] = useState({});

  function startExam() {
    let qs = examConfig.randomize
      ? shuffle(ALL_QUESTIONS).slice(0, examConfig.count)
      : ALL_QUESTIONS.slice(0, examConfig.count);
    setQuestions(qs);
    setAnswers({});
    setSubmitted({});
    setMode(MODES.EXAM);
  }

  function toggleOption(qid, opt) {
    setAnswers((prev) => {
      const current = prev[qid] || [];
      const question = questions.find((q) => q.id === qid);
      if (!question) return prev;
      let updated =
        question.type === "single"
          ? current.includes(opt) ? [] : [opt]
          : current.includes(opt)
          ? current.filter((o) => o !== opt)
          : [...current, opt];
      return { ...prev, [qid]: updated };
    });
  }

  function submitAnswer(qid) {
    setSubmitted((prev) => ({ ...prev, [qid]: true }));
  }

  function isCorrect(q) {
    const sel = answers[q.id] || [];
    if (sel.length === 0) return false;
    const sortedAns = [...q.ans].sort();
    const sortedSel = [...sel].sort();
    if (sortedAns.length !== sortedSel.length) return false;
    return sortedAns.every((a, i) => a === sortedSel[i]);
  }

  return (
    <PasswordGate>
      <div style={{ padding: 20 }}>
        {mode === MODES.HOME && (
          <>
            <h1>Welcome to CIS-VR Practice</h1>
            <p>Total Questions Available: {ALL_QUESTIONS.length}</p>
            <p>
              Select number of questions:
              {[20, 30, 50, 72, 142].map((n) => (
                <button
                  key={n}
                  style={{ marginLeft: 8, backgroundColor: examConfig.count === n ? "lightblue" : "white" }}
                  onClick={() => setExamConfig((c) => ({ ...c, count: n }))}
                >
                  {n}
                </button>
              ))}
            </p>
            <p>
              Order:
              <button
                style={{ marginLeft: 8, backgroundColor: examConfig.randomize ? "lightblue" : "white" }}
                onClick={() => setExamConfig((c) => ({ ...c, randomize: true }))}
              >
                Random
              </button>
              <button
                style={{ marginLeft: 8, backgroundColor: !examConfig.randomize ? "lightblue" : "white" }}
                onClick={() => setExamConfig((c) => ({ ...c, randomize: false }))}
              >
                Sequential
              </button>
            </p>
            <button onClick={startExam} style={{ marginTop: 20, padding: "10px 20px" }}>
              Start Practice Exam
            </button>
          </>
        )}
        {mode === MODES.EXAM && (
          <>
            <h2>Practice Exam — {questions.length} Questions</h2>
            <button onClick={() => setMode(MODES.HOME)} style={{ marginBottom: 20 }}>
              ← Back to Home
            </button>
            {questions.map((q) => (
              <QuestionCard
                key={q.id}
                q={q}
                sel={answers[q.id] || []}
                isSubmitted={submitted[q.id] || false}
                correct={isCorrect(q)}
                onToggle={toggleOption}
                onSubmit={submitAnswer}
              />
            ))}
          </>
        )}
      </div>
    </PasswordGate>
  );
}

export default App;
